blank_issues_enabled: false
contact_links:
  - name: "ğŸ™‹â€â™€ï¸ Question"
    url: https://github.com/foxglove/mcap/discussions
    about: Search or start a discussion
  - name: "ğŸš€ Feature request"
    url: https://github.com/foxglove/mcap/discussions
    about: Share a new idea
  - name: "ğŸ“š Stack Exchange"
    url: https://robotics.stackexchange.com/questions/ask
    about: Get help from the robotics community
  - name: "ğŸ’¬ Live chat"
    url: https://foxglove.dev/chat
    about: Join the discussion in our Discord community
